### PR TITLE
WIP - Catching up Viewport with the iOS code

### PR DESCRIPTION
**Pull request by udipl**
This is an initial PR for some work intended to make the iOS app work with the current Viewport code.

See the [related PR on paperless-ios](https://github.com/paperlesspost/paperless-ios/pull/2150).

### CODE REVIEW

**Comment by udipl** [comment]
This PR alsos include a merge from root/master.

**Comment by SRandazzo** [comment]
@udipl Is any of this content that we would want to PR back to Ejecta's main fork?

No need to do it anytime soon, just inquiring for curiosity

**Comment by SRandazzo** [comment]
Looks good as far as I can tell, Will merge this in now

**Comment by udipl** [comment]
@SRandazzo my main contribution is in CanvasContext2D - parsing comma-delimited list of fonts. The spec requires that, and the root Ejecta implementation would break with presented with a comma. The thing is that my fix just ensures that it doesn't break, but doesn't actually implement the font fallback semantics indicated [in the spec](https://html.spec.whatwg.org/multipage/scripting.html#dom-context-2d-font).

**Pull request merged**
